
def save_model(MainModel, network_filepath, weight_filepath, dump_filepath):
    dump_net = dump_filepath + '.cfg'
    dump_weight = dump_filepath + '.weights'
    dump_net = str(dump_net)
    dump_weight = str(dump_weight)
    MainModel.make_net(dump_net)
    MainModel.gen_weight(weight_filepath, dump_weight)
    print('Darknet model files are saved as [{}] and [{}], generated by [{}.py] and [{}].'.format(
        dump_net, dump_weight, network_filepath, weight_filepath))
