export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM';
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;


export const DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM';
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;

export const IMPORT_MODEL = "IMPORT_MODEL" 
export type IMPORT_MODEL = typeof IMPORT_MODEL

export const SELECT_LAYER = "SELECT_LAYER" 
export type SELECT_LAYER = typeof SELECT_LAYER



// style config
export const BG_COLOR="#333";
export const FG_COLOR=["#49a9ee", "#F29C30", "#75C277", "#DA5246"] 